import * as React from 'react';
import { Timeline, type TimelineEvent } from '@/components/timeline';
import { PlayCircle, Clock, CheckCircle2, User, UserCheck } from 'lucide-react';
import type { Report } from '../../types/report.types';
import { formatDate } from '@/utils';

export const ReportApprovalStatus: React.FC<{ report: Report }> = ({ report }) => {
  const events: TimelineEvent[] = [
    { id: '1', title: 'Created', date: formatDate(report.generated_at), icon: PlayCircle, isActive: false, description: 'Report generated by AI.' },
  ];

  if (report.status === 'PENDING_APPROVAL' || report.status === 'FINALIZED' || report.status === 'REVISION_REQUESTED') {
    events.push({ id: '2', title: 'Running', date: formatDate(report.generated_at), icon: Clock, isActive: false, description: 'Pipeline execution finished.' });
  }

  const isPending = report.status === 'PENDING_APPROVAL';
  const isApproved = report.status === 'FINALIZED';

  events.push({ 
    id: '3', 
    title: 'Waiting for Manager', 
    date: isPending ? 'Pending' : (isApproved ? formatDate(report.approved_at || report.generated_at) : ''), 
    icon: User, 
    isActive: isPending,
    description: isPending ? 'Manager review required.' : ''
  });

  events.push({ 
    id: '4', 
    title: 'Waiting for HR', 
    date: 'Pending', 
    icon: UserCheck, 
    isActive: false 
  });
  
  if (isApproved) {
    events.push({ id: '5', title: 'Approved', date: formatDate(report.approved_at || ''), icon: CheckCircle2, isActive: false });
    events.push({ id: '6', title: 'Completed', date: formatDate(report.approved_at || ''), icon: CheckCircle2, isActive: false });
  } else {
    events.push({ id: '5', title: 'Approved', date: 'Pending', icon: CheckCircle2, isActive: false });
    events.push({ id: '6', title: 'Completed', date: 'Pending', icon: CheckCircle2, isActive: false });
  }

  return (
    <section id="approval" className="scroll-mt-24 space-y-4">
      <h2 className="text-2xl font-semibold tracking-tight">Approval History</h2>
      <div className="p-6 rounded-lg border border-border/50 bg-card max-w-4xl">
        <Timeline events={events} />
        {isPending && (
          <div className="mt-6 pt-6 border-t border-border/50 flex gap-4">
            <button
              className="btn btn-primary bg-primary text-primary-foreground px-4 py-2 rounded font-medium"
              onClick={async () => {
                const { reportApi } = await import('@/features/reports/api/report.api');
                try {
                  await reportApi.approve(report.id, {
                    action: 'APPROVE',
                    reason: 'Approved via dashboard',
                    idempotency_key: crypto.randomUUID()
                  });
                  window.location.reload();
                } catch (err) {
                  alert('Approval failed');
                }
              }}
            >
              Approve Report
            </button>
          </div>
        )}
      </div>
    </section>
  );
};
