"""FairTrace — All Enum Definitions (single import point)"""
import enum


class UserRole(str, enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ORG_ADMIN = "ORG_ADMIN"
    HR_ADMIN = "HR_ADMIN"
    MANAGER = "MANAGER"
    EMPLOYEE = "EMPLOYEE"
    REVIEWER = "REVIEWER"


class ReviewCycleStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReviewStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    AI_PROCESSING = "AI_PROCESSING"
    MANAGER_REVIEW = "MANAGER_REVIEW"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EMPLOYEE_ACKNOWLEDGED = "EMPLOYEE_ACKNOWLEDGED"
    COMPLETED = "COMPLETED"


class GoalStatus(str, enum.Enum):
    NOT_STARTED = "NOT_STARTED"
    ON_TRACK = "ON_TRACK"
    AT_RISK = "AT_RISK"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"


class FeedbackType(str, enum.Enum):
    PEER = "PEER"
    MANAGER = "MANAGER"
    SELF = "SELF"
    GENERAL = "GENERAL"


class ReportStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    FINALIZED = "FINALIZED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REJECTED = "REJECTED"


class DocumentStatus(str, enum.Enum):
    UPLOADING = "UPLOADING"
    VALIDATING = "VALIDATING"
    STORED = "STORED"
    PROCESSING = "PROCESSING"
    PARSED = "PARSED"
    INDEXED = "INDEXED"
    FAILED = "FAILED"
    DELETED = "DELETED"


class ParsingStatus(str, enum.Enum):
    PENDING = "PENDING"
    PARSING = "PARSING"
    PARSED = "PARSED"
    FAILED = "FAILED"


class InputType(str, enum.Enum):
    SELF_ASSESSMENT = "SELF_ASSESSMENT"
    MANAGER_NOTE = "MANAGER_NOTE"
    PEER_REVIEW = "PEER_REVIEW"
    PROJECT_OUTCOME = "PROJECT_OUTCOME"
    GOAL = "GOAL"
    MEETING_NOTE = "MEETING_NOTE"


class PerformanceDimension(str, enum.Enum):
    TECHNICAL = "TECHNICAL"
    COLLABORATION = "COLLABORATION"
    LEADERSHIP = "LEADERSHIP"
    DELIVERY = "DELIVERY"
    GROWTH = "GROWTH"


class BiasType(str, enum.Enum):
    RECENCY = "RECENCY"
    HALO = "HALO"
    HORN = "HORN"
    LENIENCY = "LENIENCY"
    SEVERITY = "SEVERITY"
    UNSUPPORTED = "UNSUPPORTED"
    IMBALANCE = "IMBALANCE"


class Severity(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ConfidenceLevel(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class AuditEventType(str, enum.Enum):
    REVIEW_CYCLE_CREATED = "REVIEW_CYCLE_CREATED"
    REVIEW_CYCLE_UPDATED = "REVIEW_CYCLE_UPDATED"
    REVIEW_CYCLE_CANCELLED = "REVIEW_CYCLE_CANCELLED"
    INPUT_SUBMITTED = "INPUT_SUBMITTED"
    PIPELINE_TRIGGERED = "PIPELINE_TRIGGERED"
    PIPELINE_COMPLETED = "PIPELINE_COMPLETED"
    PIPELINE_FAILED = "PIPELINE_FAILED"
    AGENT_EXECUTED = "AGENT_EXECUTED"
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_APPROVED = "REPORT_APPROVED"
    REPORT_REJECTED = "REPORT_REJECTED"
    REPORT_REVISION_REQUESTED = "REPORT_REVISION_REQUESTED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    ACCESS_DENIED = "ACCESS_DENIED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"


class RetrievalStrategy(str, enum.Enum):
    SEMANTIC = "semantic"
    HYBRID = "hybrid"
    KEYWORD = "keyword"


class SearchMode(str, enum.Enum):
    STRICT = "STRICT"
    BALANCED = "BALANCED"
    EXHAUSTIVE = "EXHAUSTIVE"


class ApprovalAction(str, enum.Enum):
    APPROVE = "APPROVE"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REJECT = "REJECT"


class ChunkStrategy(str, enum.Enum):
    SEMANTIC = "SEMANTIC"
    RECURSIVE = "RECURSIVE"
    SENTENCE = "SENTENCE"

class ChunkStatus(str, enum.Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    EMBEDDED = "EMBEDDED"
    FAILED = "FAILED"

class EmbeddingStatus(str, enum.Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    EMBEDDED = "EMBEDDED"
    FAILED = "FAILED"

