"""ReviewGuard AI — All Enum Definitions (single import point)"""
import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    EMPLOYEE = "EMPLOYEE"


class ReviewCycleStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PROCESSING = "PROCESSING"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReportStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    FINALIZED = "FINALIZED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REJECTED = "REJECTED"


class DocumentStatus(str, enum.Enum):
    UPLOADING = "UPLOADING"
    VALIDATING = "VALIDATING"
    STORED = "STORED"
    PROCESSING = "PROCESSING"
    PARSED = "PARSED"
    INDEXED = "INDEXED"
    FAILED = "FAILED"
    DELETED = "DELETED"


class ParsingStatus(str, enum.Enum):
    PENDING = "PENDING"
    PARSING = "PARSING"
    PARSED = "PARSED"
    FAILED = "FAILED"


class InputType(str, enum.Enum):
    SELF_ASSESSMENT = "SELF_ASSESSMENT"
    MANAGER_NOTE = "MANAGER_NOTE"
    PEER_REVIEW = "PEER_REVIEW"
    PROJECT_OUTCOME = "PROJECT_OUTCOME"
    GOAL = "GOAL"
    MEETING_NOTE = "MEETING_NOTE"


class PerformanceDimension(str, enum.Enum):
    TECHNICAL = "TECHNICAL"
    COLLABORATION = "COLLABORATION"
    LEADERSHIP = "LEADERSHIP"
    DELIVERY = "DELIVERY"
    GROWTH = "GROWTH"


class BiasType(str, enum.Enum):
    RECENCY = "RECENCY"
    HALO = "HALO"
    HORN = "HORN"
    LENIENCY = "LENIENCY"
    SEVERITY = "SEVERITY"
    UNSUPPORTED = "UNSUPPORTED"
    IMBALANCE = "IMBALANCE"


class Severity(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ConfidenceLevel(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class AuditEventType(str, enum.Enum):
    REVIEW_CYCLE_CREATED = "REVIEW_CYCLE_CREATED"
    REVIEW_CYCLE_UPDATED = "REVIEW_CYCLE_UPDATED"
    REVIEW_CYCLE_CANCELLED = "REVIEW_CYCLE_CANCELLED"
    INPUT_SUBMITTED = "INPUT_SUBMITTED"
    PIPELINE_TRIGGERED = "PIPELINE_TRIGGERED"
    PIPELINE_COMPLETED = "PIPELINE_COMPLETED"
    PIPELINE_FAILED = "PIPELINE_FAILED"
    AGENT_EXECUTED = "AGENT_EXECUTED"
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_APPROVED = "REPORT_APPROVED"
    REPORT_REJECTED = "REPORT_REJECTED"
    REPORT_REVISION_REQUESTED = "REPORT_REVISION_REQUESTED"
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    ACCESS_DENIED = "ACCESS_DENIED"


class ApprovalAction(str, enum.Enum):
    APPROVE = "APPROVE"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    REJECT = "REJECT"

class ChunkStrategy(str, enum.Enum):
    SEMANTIC = "SEMANTIC"
    RECURSIVE = "RECURSIVE"
    SENTENCE = "SENTENCE"

class ChunkStatus(str, enum.Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    EMBEDDED = "EMBEDDED"
    FAILED = "FAILED"

class EmbeddingStatus(str, enum.Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    EMBEDDED = "EMBEDDED"
    FAILED = "FAILED"

