"""Add Document model

Revision ID: 7b0e43f7113f
Revises: 0001
Create Date: 2026-08-02 03:34:27.616016+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0e43f7113f'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'VALIDATING', 'STORED', 'PROCESSING', 'PARSED', 'INDEXED', 'FAILED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('virus_scan_status', sa.String(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_index('idx_audit_correlation', table_name='audit_events')
    op.drop_index('idx_audit_event_type', table_name='audit_events')
    op.drop_index('idx_audit_occurred', table_name='audit_events')
    op.drop_index('idx_audit_resource', table_name='audit_events')
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.drop_index('idx_bias_flags_report', table_name='bias_flags')
    op.drop_index('idx_bias_flags_severity', table_name='bias_flags')
    op.drop_index('idx_bias_flags_type', table_name='bias_flags')
    op.create_index(op.f('ix_bias_flags_bias_type'), 'bias_flags', ['bias_type'], unique=False)
    op.create_index(op.f('ix_bias_flags_report_id'), 'bias_flags', ['report_id'], unique=False)
    op.create_index(op.f('ix_bias_flags_review_input_id'), 'bias_flags', ['review_input_id'], unique=False)
    op.create_index(op.f('ix_bias_flags_severity'), 'bias_flags', ['severity'], unique=False)
    op.drop_index('idx_citations_claim', table_name='evidence_citations')
    op.drop_index('idx_citations_input', table_name='evidence_citations')
    op.create_index(op.f('ix_evidence_citations_claim_id'), 'evidence_citations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_citations_review_input_id'), 'evidence_citations', ['review_input_id'], unique=False)
    op.drop_index('idx_claims_dimension', table_name='performance_claims')
    op.drop_index('idx_claims_report', table_name='performance_claims')
    op.create_index(op.f('ix_performance_claims_dimension'), 'performance_claims', ['dimension'], unique=False)
    op.create_index(op.f('ix_performance_claims_report_id'), 'performance_claims', ['report_id'], unique=False)
    op.drop_index('idx_reports_current', table_name='reports')
    op.drop_index('idx_reports_cycle', table_name='reports')
    op.drop_index('idx_reports_pipeline', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.create_index(op.f('ix_reports_is_current'), 'reports', ['is_current'], unique=False)
    op.create_index(op.f('ix_reports_pipeline_run_id'), 'reports', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_reports_review_cycle_id'), 'reports', ['review_cycle_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.drop_index('idx_review_cycles_employee', table_name='review_cycles')
    op.drop_index('idx_review_cycles_manager', table_name='review_cycles')
    op.drop_index('idx_review_cycles_status', table_name='review_cycles')
    op.create_index(op.f('ix_review_cycles_employee_id'), 'review_cycles', ['employee_id'], unique=False)
    op.create_index(op.f('ix_review_cycles_manager_id'), 'review_cycles', ['manager_id'], unique=False)
    op.create_index(op.f('ix_review_cycles_status'), 'review_cycles', ['status'], unique=False)
    op.drop_index('idx_review_inputs_cycle', table_name='review_inputs')
    op.drop_index('idx_review_inputs_type', table_name='review_inputs')
    op.create_index(op.f('ix_review_inputs_input_type'), 'review_inputs', ['input_type'], unique=False)
    op.create_index(op.f('ix_review_inputs_review_cycle_id'), 'review_inputs', ['review_cycle_id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_review_inputs_review_cycle_id'), table_name='review_inputs')
    op.drop_index(op.f('ix_review_inputs_input_type'), table_name='review_inputs')
    op.create_index('idx_review_inputs_type', 'review_inputs', ['input_type'], unique=False)
    op.create_index('idx_review_inputs_cycle', 'review_inputs', ['review_cycle_id'], unique=False)
    op.drop_index(op.f('ix_review_cycles_status'), table_name='review_cycles')
    op.drop_index(op.f('ix_review_cycles_manager_id'), table_name='review_cycles')
    op.drop_index(op.f('ix_review_cycles_employee_id'), table_name='review_cycles')
    op.create_index('idx_review_cycles_status', 'review_cycles', ['status'], unique=False)
    op.create_index('idx_review_cycles_manager', 'review_cycles', ['manager_id'], unique=False)
    op.create_index('idx_review_cycles_employee', 'review_cycles', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_review_cycle_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_pipeline_run_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_current'), table_name='reports')
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_index('idx_reports_pipeline', 'reports', ['pipeline_run_id'], unique=False)
    op.create_index('idx_reports_cycle', 'reports', ['review_cycle_id'], unique=False)
    op.create_index('idx_reports_current', 'reports', ['is_current'], unique=False)
    op.drop_index(op.f('ix_performance_claims_report_id'), table_name='performance_claims')
    op.drop_index(op.f('ix_performance_claims_dimension'), table_name='performance_claims')
    op.create_index('idx_claims_report', 'performance_claims', ['report_id'], unique=False)
    op.create_index('idx_claims_dimension', 'performance_claims', ['dimension'], unique=False)
    op.drop_index(op.f('ix_evidence_citations_review_input_id'), table_name='evidence_citations')
    op.drop_index(op.f('ix_evidence_citations_claim_id'), table_name='evidence_citations')
    op.create_index('idx_citations_input', 'evidence_citations', ['review_input_id'], unique=False)
    op.create_index('idx_citations_claim', 'evidence_citations', ['claim_id'], unique=False)
    op.drop_index(op.f('ix_bias_flags_severity'), table_name='bias_flags')
    op.drop_index(op.f('ix_bias_flags_review_input_id'), table_name='bias_flags')
    op.drop_index(op.f('ix_bias_flags_report_id'), table_name='bias_flags')
    op.drop_index(op.f('ix_bias_flags_bias_type'), table_name='bias_flags')
    op.create_index('idx_bias_flags_type', 'bias_flags', ['bias_type'], unique=False)
    op.create_index('idx_bias_flags_severity', 'bias_flags', ['severity'], unique=False)
    op.create_index('idx_bias_flags_report', 'bias_flags', ['report_id'], unique=False)
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.create_index('idx_audit_resource', 'audit_events', ['resource_id'], unique=False)
    op.create_index('idx_audit_occurred', 'audit_events', ['occurred_at'], unique=False)
    op.create_index('idx_audit_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('idx_audit_correlation', 'audit_events', ['correlation_id'], unique=False)
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
