"""add_embedding_fields_to_document_chunk

Revision ID: 8fe0ac08da58
Revises: 715edd2d519c
Create Date: 2026-08-02 05:20:16.705573+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe0ac08da58'
down_revision: Union[str, None] = '715edd2d519c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_provider', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_version', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_duration_ms', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_checksum', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_error')
    op.drop_column('document_chunks', 'token_count')
    op.drop_column('document_chunks', 'embedding_checksum')
    op.drop_column('document_chunks', 'embedding_duration_ms')
    op.drop_column('document_chunks', 'embedding_created_at')
    op.drop_column('document_chunks', 'embedding_dimensions')
    op.drop_column('document_chunks', 'embedding_version')
    op.drop_column('document_chunks', 'embedding_provider')
    # ### end Alembic commands ###
