"""Add idempotency and heartbeat to workflow

Revision ID: bdc668b44ec3
Revises: f3cffe7662e9
Create Date: 2026-08-13 15:29:56.169136+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc668b44ec3'
down_revision: Union[str, None] = 'f3cffe7662e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_executions', sa.Column('review_cycle_id', sa.UUID(), nullable=True))
    op.create_index('uq_active_workflow_per_cycle', 'workflow_executions', ['review_cycle_id'], unique=True, sqlite_where=sa.text("status = 'RUNNING'"), postgresql_where=sa.text("status = 'RUNNING'"))
    op.create_foreign_key(None, 'workflow_executions', 'review_cycles', ['review_cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_executions', type_='foreignkey')
    op.drop_index('uq_active_workflow_per_cycle', table_name='workflow_executions', sqlite_where=sa.text("status = 'RUNNING'"), postgresql_where=sa.text("status = 'RUNNING'"))
    op.drop_column('workflow_executions', 'review_cycle_id')
    op.drop_column('workflow_executions', 'last_heartbeat_at')
    # ### end Alembic commands ###
