"""Complete Schema

Revision ID: e1c90c9d592c
Revises: 8fe0ac08da58
Create Date: 2026-08-02 13:25:12.608543+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c90c9d592c'
down_revision: Union[str, None] = '8fe0ac08da58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=100), nullable=False),
    sa.Column('report_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'HTML', 'JSON', name='exportformat'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'FAILED', 'EXPIRED', name='exportstatus'), nullable=False),
    sa.Column('checksum', sa.String(length=256), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=1024), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_exports_workflow_id'), 'report_exports', ['workflow_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=100), nullable=False),
    sa.Column('graph_thread_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'WAITING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVISION_REQUESTED', name='workflowstatus'), nullable=False),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=True),
    sa.Column('current_retry', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_execution_id'), 'workflow_executions', ['execution_id'], unique=True)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=100), nullable=False),
    sa.Column('report_id', sa.String(length=100), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REVISION_REQUESTED', 'EXPIRED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('decision_version', sa.String(length=50), nullable=True),
    sa.Column('decision_reason', sa.String(length=2000), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('node', sa.String(length=100), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.String(length=100), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_history')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_workflow_executions_execution_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_report_exports_workflow_id'), table_name='report_exports')
    op.drop_table('report_exports')
    # ### end Alembic commands ###
