"""Add document parsing fields

Revision ID: f1b705e6a155
Revises: 7b0e43f7113f
Create Date: 2026-08-02 04:50:15.454202+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b705e6a155'
down_revision: Union[str, None] = '7b0e43f7113f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    parsing_status_enum = postgresql.ENUM('PENDING', 'PARSING', 'PARSED', 'FAILED', name='parsingstatus')
    parsing_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('documents', sa.Column('parsed_text', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('character_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('parser_used', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('parser_version', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('parse_duration_ms', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('parsing_status', parsing_status_enum, server_default='PENDING', nullable=False))
    op.add_column('documents', sa.Column('parsed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('parsing_error', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_parsing_status'), 'documents', ['parsing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_parsing_status'), table_name='documents')
    op.drop_column('documents', 'parsing_error')
    op.drop_column('documents', 'parsed_at')
    op.drop_column('documents', 'parsing_status')
    op.drop_column('documents', 'parse_duration_ms')
    op.drop_column('documents', 'parser_version')
    op.drop_column('documents', 'parser_used')
    op.drop_column('documents', 'character_count')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'parsed_text')
    
    parsing_status_enum = postgresql.ENUM('PENDING', 'PARSING', 'PARSED', 'FAILED', name='parsingstatus')
    parsing_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
