"""Phase_1_Models

Revision ID: f3cffe7662e9
Revises: e1c90c9d592c
Create Date: 2026-08-13 14:46:29.588226+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cffe7662e9'
down_revision: Union[str, None] = 'e1c90c9d592c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_execution_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='agentstatus'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'NON_CRITICAL', name='agentseverity'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_workflow_execution_id'), 'agent_executions', ['workflow_execution_id'], unique=False)
    op.add_column('evidence_citations', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.add_column('evidence_citations', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('evidence_citations', sa.Column('source_reference', sa.String(length=255), nullable=True))
    op.alter_column('evidence_citations', 'claim_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_evidence_citations_source_document_id'), 'evidence_citations', ['source_document_id'], unique=False)
    op.create_foreign_key(None, 'evidence_citations', 'documents', ['source_document_id'], ['id'])
    op.add_column('review_cycles', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_review_cycles_organization_id'), 'review_cycles', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'review_cycles', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.add_column('workflow_executions', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('workflow_executions', sa.Column('max_retries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_executions', 'max_retries')
    op.drop_column('workflow_executions', 'retry_count')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'review_cycles', type_='foreignkey')
    op.drop_index(op.f('ix_review_cycles_organization_id'), table_name='review_cycles')
    op.drop_column('review_cycles', 'organization_id')
    op.drop_constraint(None, 'evidence_citations', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_citations_source_document_id'), table_name='evidence_citations')
    op.alter_column('evidence_citations', 'claim_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('evidence_citations', 'source_reference')
    op.drop_column('evidence_citations', 'source_type')
    op.drop_column('evidence_citations', 'source_document_id')
    op.drop_index(op.f('ix_agent_executions_workflow_execution_id'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
